apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: novus-runtimes
  namespace: argocd
spec:
  destinations:
    - name: "*"
      namespace: "*"
      server: https://kubernetes.default.svc
  sourceRepos:
    - "*"
  sourceNamespaces:
    - "argocd"