apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: novus-system
  namespace: argocd
spec:
  description: "Project containing novus system applications and services."
  destinations:
    - name: "*"
      namespace: "*"
      server: https://kubernetes.default.svc
  sourceRepos:
    - "*"
  sourceNamespaces:
    - "argocd"
