apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: generate-runtime-argocd-project
  annotations:
    policies.kyverno.io/title: Generate ArgoCD Project
    policies.kyverno.io/category: novus-runtime
    policies.kyverno.io/description: >-
      For every runtime created there should exist one ArgoCD project
      that will contain the user defined application deployments. This
      rule will create that for each namespace marked as a Novus runtime.
spec:
  rules:
    - name: generate-runtime-argocd-project
      match:
        any:
          - resources:
              kinds:
                - Namespace
              selector:
                matchLabels:
                  novus.legogroup.io/namespace-type: managed-runtime

      context:
        - name: runtime
          variable:
            jmesPath: request.object.metadata

      generate:
        kind: AppProject
        apiVersion: argoproj.io/v1alpha1
        name: "{{ request.object.metadata.name }}"
        namespace: argocd
        synchronize: true
        data:
          metadata:
            ownerReferences:
              - apiVersion: v1
                kind: Namespace
                name: "{{ runtime.name }}"
                uid: "{{ runtime.uid }}"
          spec:
            destinations:
              - name: "*"
                namespace: "{{ runtime.name }}"
                server: https://kubernetes.default.svc
            sourceRepos:
              - "*"
            sourceNamespaces:
              - "{{ runtime.name }}"
