apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: runtime-generate-argocd-project
spec:
  rules:
    - name: runtime-generate-argocd-project
      match:
        any:
          - resources:
              kinds:
                - Namespace
              selector:
                matchLabels:
                  novus.legogroup.io/namespace-type: managed-runtime
      generate:
        kind: AppProject
        apiVersion: argoproj.io/v1alpha1
        name: "{{ request.object.metadata.name }}"
        namespace: argocd
        synchronize: true
        data:
          metadata:
            ownerReferences:
              - apiVersion: v1
                kind: Namespace
                name: "{{request.object.metadata.name}}"
                uid: "{{request.object.metadata.uid}}"
          spec:
            destinations:
              - name: "*"
                namespace: "{{ request.object.metadata.name }}"
                server: https://kubernetes.default.svc
            sourceRepos:
              - "*"
            sourceNamespaces:
              - "{{ request.object.metadata.name }}"
