apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: runtime-mutate-argocd-applications
spec:
  rules:
    - name: runtime-mutate-argocd-applications
      match:
        any:
          - resources:
              kinds:
                - Application
              namespaceSelector:
                matchExpressions:
                  - key: "novus.legogroup.io/namespace-type"
                    operator: In
                    values:
                      - managed-runtime
      mutate:
        patchStrategicMerge:
          spec:
            project: '{{ request.object.metadata.namespace }}'
            destination:
              namespace: '{{ request.object.metadata.namespace }}'
              server: "https://kubernetes.default.svc"
